/*
 * Author: Zoe
 * Purpose: This controller handles calling the stored procedures in the entity framework 
 *			and sends the information to the view to be turned into a google chart. 
 */
using System.Collections.Generic;
using System.Web.Mvc;
using StaffingPlanner.Models;

namespace StaffingPlanner.Controllers
{
    public class StatisticsController : Controller
    {
        private DEV_ClientOpportunitiesEntities db = new DEV_ClientOpportunitiesEntities();

        /* GET: Statistics */
        public ActionResult Index()
        {
            return View();
        }

		/*
		 *Pulls the Opportunity Status Chart information using the STATS_OPPORTUNITY_STATUS storedproc 
		 *and makes it available to be received by an AJAX call.
		 */
		[HttpGet]
		public ActionResult OpportunityStatusChartData()
		{
			var results = db.Database.SqlQuery<OpportunityStatusStats>("STATS_OPPORTUNITY_STATUS");
			List<object> chartData = new List<object>
			{
				new object[] { "Status", "Count" }
			};
			foreach (OpportunityStatusStats res in results)
			{
				if (res.Status_Count >= 1)
				{
					chartData.Add(new object[] { res.Opportunity_Status_Name, res.Status_Count });
				}
				else
				{
					chartData.Add(new object[] { res.Opportunity_Status_Name, 0 });
				}
			}

			//Arbitraty hardcoded information for testing
			//List<object> chartData = new List<object>(3)
			//{
			//	new object[] { "Status", "Count" },
			//	new object[] { "Sold", 9 },
			//	new object[] { "Lost Opportunity", 3 },
			//	new object[] {"On-Hold", 6 },
			//	new object[] {"Active", 4 }
			//};
			return Json(chartData, JsonRequestBehavior.AllowGet);
		}

		/*
		*Pulls the Lost Opportunity Chart information using the STATS_LOST_OPPORTUNITY storedproc 
		*and makes it available to be received by an AJAX call.
		*/
		[HttpGet]
		public ActionResult LostOpportunityChartData()
		{
			var results = db.Database.SqlQuery<LostOpportunityStats>("STATS_LOST_OPPORTUNITY");
			List<object> chartData = new List<object>
			{
				new object[] { "Reason", "Count" }
			};
			foreach (LostOpportunityStats res in results)
			{
				if (res.Reason_Count >= 1)
				{
					chartData.Add(new object[] { res.Reason, res.Reason_Count });
				}
				else
				{
					chartData.Add(new object[] { res.Reason, 0 });
				}
			}

			//Arbitraty hardcoded information for testing
			//List<object> chartData = new List<object>(3)
			//{
			//	new object[] { "Reason", "Count" },
			//	new object[] { "High Bill Rate", 10 },
			//	new object[] { "Deadline Miss", 3 },
			//	new object[] {"Recruitment Delay", 7 },
			//	new object[] {"No Candidate", 2 },
			//	new object[] {"No Help From Practice", 5 }
			//};
			return Json(chartData, JsonRequestBehavior.AllowGet);
		}

		/*
		*Pulls the Portfolio Chart information using the STATS_PORTFOLIO storedproc 
		*and makes it available to be received by an AJAX call.
		 */
		[HttpGet]
		public ActionResult PortfolioChartData()
		{
			var results = db.Database.SqlQuery<PortfolioStats>("STATS_PORTFOLIO");
			List<object> chartData = new List<object>
			{
				new object[] { "Client", "Amount" }
			};
			foreach (PortfolioStats res in results)
			{
				if (res.Value >= 1)
				{
					chartData.Add(new object[] { res.Client, res.Value });
				}
				else
				{
					chartData.Add(new object[] { res.Client, 0 });
				}
			}

			//Arbitraty hardcoded information for testing
			//List<object> chartData = new List<object>(3)
			//{
			//	new object[] { "Sub-business", "Amount" },
			//	new object[] { "Healthcare", 41 },
			//	new object[] { "Power", 16 },
			//	new object[] {"BHGE", 7 },
			//	new object[] {"Lighting", 6 },
			//	new object[] {"Life Sciences", 30 }
			//};
			return Json(chartData, JsonRequestBehavior.AllowGet);
		}

		/*
		*Hardcodes the data to be shown on the Profit Chart.
		* TODO: Implement stored procedure data retrieval once the procedure is written.
		*/
		[HttpGet]
		public ActionResult ProfitChartData()
		{
			List<object> chartData = new List<object>(3)
			{
				new object[] { "Quarter", "Amount" },
				new object[] { "Q1", 0 },
				new object[] { "Q2", 0 },
				new object[] {"Q3", 0 },
				new object[] {"Q4", 0 }
			};
			return Json(chartData, JsonRequestBehavior.AllowGet);
		}

		/* Autogenerated Dispose Function*/
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
