//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffingPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT_DETAILS()
        {
            this.OPPORTUNITY_CATALOG = new HashSet<OPPORTUNITY_CATALOG>();
        }
    
        public int CLIENT_ID { get; set; }
        public string CLIENT_NAME { get; set; }
        public string CLIENT_SUB_BUSINESS { get; set; }
        public bool CLIENT_STATUS { get; set; }
        public string LAST_EDITED_BY { get; set; }
        public System.DateTime LAST_EDITED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPPORTUNITY_CATALOG> OPPORTUNITY_CATALOG { get; set; }
    }
}
