//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffingPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTANT
    {
        public int CONSULTANT_ID { get; set; }
        public string CONSULTANT_NAME { get; set; }
        public string CONSULTANT_PRACTICE { get; set; }
        public Nullable<System.DateTime> SOGETI_START_DATE { get; set; }
        public bool CONSULTANT_EMPLOYMENT_STATUS { get; set; }
        public string LAST_EDITED_BY { get; set; }
        public System.DateTime LAST_EDITED_DATE { get; set; }
    }
}
