//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffingPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPPORTUNITY_CATALOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPPORTUNITY_CATALOG()
        {
            this.OPPORTUNITY_GROUP = new HashSet<OPPORTUNITY_GROUP>();
            this.LOST_REASON = new HashSet<LOST_REASON>();
        }
    
        public int OPPORTUNITY_ID { get; set; }
        public int CLIENT_ID { get; set; }
        public int OPPORTUNITY_STATUS_ID { get; set; }
        public string LOCATION { get; set; }
        public string SPONSOR { get; set; }
        public string OPPORTUNITY_NAME { get; set; }
        public string OPPORTUNITY_PRACTICE { get; set; }
        public Nullable<decimal> OPPORTUNITY_VALUE { get; set; }
        public bool OPPORTUNITY_STATUS { get; set; }
        public string OPPORTUNITY_COMMENT { get; set; }
        public string OPPORTUNITY_PRIORITY { get; set; }
        public string OPPORTUNITY_TYPE { get; set; }
        public Nullable<int> NUMBER_OF_REQUIRED_ROLES { get; set; }
        public string LAST_EDITED_BY { get; set; }
        public System.DateTime LAST_EDITED_DATE { get; set; }
    
        public virtual CLIENT_DETAILS CLIENT_DETAILS { get; set; }
        public virtual OPPORTUNITY_STATUS OPPORTUNITY_STATUS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPPORTUNITY_GROUP> OPPORTUNITY_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOST_REASON> LOST_REASON { get; set; }
    }
}
