//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffingPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPPORTUNITY_STATUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OPPORTUNITY_STATUS()
        {
            this.OPPORTUNITY_CATALOG = new HashSet<OPPORTUNITY_CATALOG>();
        }
    
        public int OPPORTUNITY_STATUS_ID { get; set; }
        public string OPPORTUNITY_STATUS_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPPORTUNITY_CATALOG> OPPORTUNITY_CATALOG { get; set; }
    }
}
