//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffingPlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGNUP_INFO
    {
        public int USER_ID { get; set; }
        public int USER_PRIVILEGE_ID { get; set; }
        public string USERNAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public Nullable<bool> USER_STATUS { get; set; }
        public Nullable<System.DateTime> LAST_LOGON { get; set; }
    
        public virtual USER_PRIVILEGE USER_PRIVILEGE { get; set; }
    }
}
